routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('dashboard','DashboardController@index');
    Route::resource('brand','admin\BrandController');
    Route::resource('fileType','admin\FileTypeController');
    Route::resource('instruction','admin\InstructionController');
    Route::resource('device','admin\DeviceController');
    Route::resource('file','admin\FileController');

app/Http/Controllers/admin/InstructionController.php
<?php

namespace App\Http\Controllers\admin;

use App\admin\Instruction;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class InstructionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['instructions'] = Instruction::all();
        return view('admin/instruction/index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin/instruction/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data['instructions_title'] = $request->instructions_title;
        $data['details'] = $request->details;

        Instruction::create($data);
        return redirect()->route('instruction.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['instruction'] = Instruction::findOrfail($id);
        return view('admin/instruction/edit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data['instructions_title'] = $request->instructions_title;
        $data['details'] = $request->details;

        Instruction::findOrFail($id)->update($data);
        return redirect()->route('instruction.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Instruction::findOrfail($id)->delete();
        return redirect()->route('instruction.index');
    }
}

resources/views/admin/instruction/create.blade.php
@extends('layouts.admin.master')
@section('title','Add new instruction')
@section('content')
    <section class="content">
        <div class="row">

            <div class="col-md-6">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Add new instruction</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    <form role="form" action="{{ route('instruction.store') }}" method="post">
                        @csrf
                        <div class="box-body">
                            <div class="form-group">
                                <label for="instruction">Instruction Title</label>
                                <input type="text" class="form-control" id="instruction" placeholder="Instruction Title" name="instructions_title">
                            </div>
                            <div class="form-group">
                                <label for="details">Details</label>
                                <input type="text" class="form-control" id="details" placeholder="Details" name="details">
                            </div>
                        </div>
                        <!-- /.box-body -->

                        <div class="box-footer">
                            <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                    </form>
                </div>
                <!-- /.box -->
            </div>

        </div>
        <!-- /.row -->
    </section>
@endsection

resources/views/admin/instruction/edit.blade.php
@extends('layouts.admin.master')
@section('title','Edit Instruction')
@section('content')
    <section class="content">
        <div class="row">

            <div class="col-md-6">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Edit instruction</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    <form role="form" action="{{ route('instruction.update',$instruction->id) }}" method="post">
                        @csrf
                        @method('put')
                        <div class="box-body">
                            <div class="form-group">
                                <label for="instruction">Instruction Title</label>
                                <input type="text" class="form-control" id="instruction" placeholder="Instruction Title" name="instructions_title" value="{{ $instruction->instructions_title }}">
                            </div>
                            <div class="form-group">
                                <label for="details">Details</label>
                                <input type="text" class="form-control" id="details" placeholder="Details" name="details" value="{{ $instruction->details }}">
                            </div>
                        </div>
                        <!-- /.box-body -->

                        <div class="box-footer">
                            <button type="submit" class="btn btn-primary">Update</button>
                        </div>
                    </form>
                </div>
                <!-- /.box -->
            </div>

        </div>
        <!-- /.row -->
    </section>
@endsection

resources/views/admin/instruction/index.blade.php
@extends('layouts.admin.master')
@section('title','Add Instruction')
@section('content')
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Instructions</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap"><div class="row"><div class="col-sm-6"></div><div class="col-sm-6"></div></div><div class="row"><div class="col-sm-12"><table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                                        <thead>
                                        <tr role="row">
                                            <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Brand name: activate to sort column descending">Instruction Title</th>
                                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Brand details: activate to sort column ascending">Details</th>
                                            <th  tabindex="0" aria-controls="example2" rowspan="1" colspan="1">Action</th>
                                        </thead>
                                        <tbody>
                                        @foreach($instructions as $instruction)
                                            <tr role="row" class="odd">
                                                <td class="sorting_1">{{ $instruction->instructions_title }}</td>
                                                <td>{{ $instruction->details }}</td>
                                                <td>

                                                    <a href="{{ route('instruction.edit',$instruction->id) }}" class="btn btn-primary" data-toggle="tooltip">
                                                        Edit
                                                    </a>
                                                    <form class="d-inline-block" action="{{ route('instruction.destroy',$instruction->id) }}" method="post">
                                                        @csrf
                                                        @method('delete')
                                                        <button class="btn btn-danger">Delete</button>
                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-5">
                                    <div class="dataTables_info" id="example2_info" role="status" aria-live="polite">Showing 1 to 10 of 57 entries
                                    </div>
                                </div>
                                <div class="col-sm-7">
                                    <div class="dataTables_paginate paging_simple_numbers" id="example2_paginate">
                                        <ul class="pagination">
                                            paginate part
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.box-body -->
                </div>

            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
@endsection