routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('dashboard','DashboardController@index');
    Route::resource('brand','admin\BrandController');
    Route::resource('fileType','admin\FileTypeController');
    Route::resource('instruction','admin\InstructionController');
    Route::resource('device','admin\DeviceController');
    Route::resource('file','admin\FileController');

app/Http/Controllers/admin/FileController.php
<?php

namespace App\Http\Controllers\admin;

use App\admin\Device;
use App\admin\File;
use App\admin\FileType;
use App\admin\Instruction;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class FileController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['files'] = File::all();
        return view('admin/file/index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['devices'] = Device::all();
        $data['types'] = FileType::all();
        $data['instructions'] = Instruction::all();

        return view('admin/file/create',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data['file_name'] = $request->file_name;
        $data['version'] = $request->version;
        $data['os_version'] = $request->os_version;
        $data['price'] = $request->price;
        $data['file_size'] = $request->file_size;
        $data['device_id'] = $request->device_id;
        $data['type_id'] = $request->type_id;
        $data['instruction_id'] = $request->instruction_id;

        File::create($data);
        return redirect()->route('file.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['devices'] = Device::all();
        $data['types'] = FileType::all();
        $data['instructions'] = Instruction::all();
        $data['file'] = File::findorfail($id);

        return view('admin/file/edit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data['file_name'] = $request->file_name;
        $data['version'] = $request->version;
        $data['os_version'] = $request->os_version;
        $data['price'] = $request->price;
        $data['file_size'] = $request->file_size;
        $data['device_id'] = $request->device_id;
        $data['type_id'] = $request->type_id;
        $data['instruction_id'] = $request->instruction_id;

        File::findOrfail($id)->update($data);
        return redirect()->route('file.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        File::findOrfail($id)->delete();
        return redirect()->route('file.index');
    }
}

resources/views/admin/file/create.blade.php
@extends('layouts.admin.master')
@section('title','Add File')
@section('content')
    <section class="content">
        <div class="row">

            <div class="col-md-6">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Add File</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    <form role="form" action="{{ route('file.store') }}" method="post">
                        @csrf
                        <div class="box-body">
                            <div class="form-group">
                                <label for="brandName">File Name</label>
                                <input type="text" class="form-control" id="fileName" placeholder="File Name" name="file_name">
                            </div>

                            <div class="form-group">
                                <label for="version">Version</label>
                                <input type="text" class="form-control" id="version" placeholder="Version" name="version">
                            </div>

                            <div class="form-group">
                                <label for="osversion">OS Version</label>
                                <input type="text" class="form-control" id="osversion" placeholder="OS Version" name="os_version">
                            </div>

                            <div class="form-group">
                                <label for="price">Price</label>
                                <input type="text" class="form-control" id="price" placeholder="Price" name="price" value="Free">
                            </div>

                            <div class="form-group">
                                <label for="fileSiza">File size</label>
                                <input type="text" class="form-control" id="fileSiza" placeholder="File size" name="file_size">
                            </div>

                            <div class="form-group">
                                <label>Device</label>
                                <select class="form-control" name="device_id">
                                    <option value="">Select Device</option>
                                    @foreach($devices as $device)
                                        <option value="{{ $device->id }}">{{ $device->name }}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="form-group">
                                <label>File type</label>
                                <select class="form-control" name="type_id">
                                    <option value="">Select type</option>
                                    @foreach($types as $type)
                                        <option value="{{ $type->id }}">{{ $type->type_name }}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="form-group">
                                <label>Instruction</label>
                                <select class="form-control" name="instruction_id">
                                    <option value="">Select instruction</option>
                                    @foreach($instructions as $instruction)
                                        <option value="{{ $instruction->id }}">{{ $instruction->instructions_title }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <!-- /.box-body -->

                        <div class="box-footer">
                            <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                    </form>
                </div>
                <!-- /.box -->
            </div>

        </div>
        <!-- /.row -->
    </section>
@endsection

resources/views/admin/file/edit.blade.php
@extends('layouts.admin.master')
@section('title','Edit file')
@section('content')
    <section class="content">
        <div class="row">

            <div class="col-md-6">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Edit File</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    <form role="form" action="{{ route('file.update',$file->id) }}" method="post">
                        @csrf
                        @method('put')
                        <div class="box-body">
                            <div class="form-group">
                                <label for="brandName">File Name</label>
                                <input type="text" class="form-control" value="{{ $file->file_name }}" id="fileName" placeholder="File Name" name="file_name">
                            </div>

                            <div class="form-group">
                                <label for="version">Version</label>
                                <input type="text" class="form-control" value="{{ $file->version }}" id="version" placeholder="Version" name="version">
                            </div>

                            <div class="form-group">
                                <label for="osversion">OS Version</label>
                                <input type="text" class="form-control" value="{{ $file->os_version }}" id="osversion" placeholder="OS Version" name="os_version">
                            </div>

                            <div class="form-group">
                                <label for="price">Price</label>
                                <input type="text" class="form-control" value="{{ $file->price }}" id="price" placeholder="Price" name="price" value="Free">
                            </div>

                            <div class="form-group">
                                <label for="fileSiza">File size</label>
                                <input type="text" class="form-control" value="{{ $file->file_size }}" id="fileSiza" placeholder="File size" name="file_size">
                            </div>

                            <div class="form-group">
                                <label>Device</label>
                                <select class="form-control" name="device_id">
                                    <option value="">Select Device</option>
                                    @foreach($devices as $device)
                                        <option value="{{ $device->id }}" {{ $device->id == $file->device_id ? 'selected="selected"' : '' }}>{{ $device->name }}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="form-group">
                                <label>File type</label>
                                <select class="form-control" name="type_id">
                                    <option value="">Select type</option>
                                    @foreach($types as $type)
                                        <option value="{{ $type->id }}" {{ $type->id == $file->type_id ? 'selected="selected"' : '' }}>{{ $type->type_name }}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="form-group">
                                <label>Instruction</label>
                                <select class="form-control" name="instruction_id">
                                    <option value="">Select instruction</option>
                                    @foreach($instructions as $instruction)
                                        <option value="{{ $instruction->id }}" {{ $instruction->id == $file->instruction_id ? 'selected="selected"' : ''}}>{{ $instruction->instructions_title }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <!-- /.box-body -->

                        <div class="box-footer">
                            <button type="submit" class="btn btn-primary">Update</button>
                        </div>
                    </form>
                </div>
                <!-- /.box -->
            </div>

        </div>
        <!-- /.row -->
    </section>
@endsection

resources/views/admin/file/index.blade.php
@extends('layouts.admin.master')
@section('title','Files')
@section('content')
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Files list</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap"><div class="row"><div class="col-sm-6"></div><div class="col-sm-6"></div></div><div class="row"><div class="col-sm-12"><table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                                        <thead>
                                        <tr role="row">
                                            <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Brand name: activate to sort column descending">File name</th>
                                            <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Brand name: activate to sort column descending">Version</th>
                                            <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Brand name: activate to sort column descending">OS version</th>
                                            <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Brand name: activate to sort column descending">Price</th>
                                            <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Brand name: activate to sort column descending">File size (KB)</th>
                                            <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Brand name: activate to sort column descending">Device</th>
                                            <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Brand name: activate to sort column descending">File type</th>
                                            <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Brand name: activate to sort column descending">Instruction</th>

                                            <th  tabindex="0" aria-controls="example2" rowspan="1" colspan="1">Action</th>
                                        </thead>
                                        <tbody>
                                        @foreach($files as $file)
                                        <tr role="row" class="odd">
                                            <td class="sorting_1">{{ $file->file_name }}</td>
                                            <td>{{ $file->version }}</td>
                                            <td>{{ $file->os_version }}</td>
                                            <td>{{ $file->price }}</td>
                                            <td>{{ $file->file_size }}</td>
                                            <td>{{ $file->device->name }}</td>
                                            <td>{{ $file->ftype->type_name ?? 'Problem here' }}</td>{{--, id asche but related type name asche na--}}
                                            <td>{{ $file->instruction->instructions_title }}</td>
                                            <td>

                                                <a href="{{ route('file.edit',$file->id) }}" class="btn btn-primary" data-toggle="tooltip">
                                                    Edit
                                                </a>
                                                <form class="d-inline-block" action="{{ route('file.destroy',$file->id) }}" method="post">
                                                    @csrf
                                                    @method('delete')
                                                    <button class="btn btn-danger">Delete</button>
                                                </form>
                                            </td>
                                        </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                         </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-5">
                            <div class="dataTables_info" id="example2_info" role="status" aria-live="polite">Showing 1 to 10 of 57 entries
                            </div>
                        </div>
                        <div class="col-sm-7">
                            <div class="dataTables_paginate paging_simple_numbers" id="example2_paginate">
                                <ul class="pagination">
                                    paginate part
                                </ul>
                            </div>
                        </div>
                    </div>
                        </div>
                    </div>
                    <!-- /.box-body -->
                </div>

            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
@endsection